/** Leaked Managed Shell Detector
 ** (c) 2024 Sator Imaging, Licensed under the MIT License
 ** https://github.com/sator-imaging/Unity-Fundamentals

Try to find leaked managed shell potentials and generate disposing method code template.
Designed to work in conjunction with ManagedShell builtin template.


HOW TO USE
==========
Select one of the the following menu commands.
- `Unity Editor > Sator Imaging > Tests > Report Leaked Managed Shell Potentials`
- `Project View > Leaked Managed Shell Detector`

 */

#if UNITY_EDITOR && UNITY_2021_3_OR_NEWER

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;
using Object = UnityEngine.Object;

namespace SatorImaging.UnityFundamentals.Editor
{
    public static class LeakedManagedShellDetector
    {
        const string MENU_MAIN = "Sator Imaging/Tests/Report Leaked Managed Shell Potentials";
        const string MENU_ASSETS = "Assets/Leaked Managed Shell Detector";

        readonly static BindingFlags BIND_FLAGS
            = BindingFlags.Public
            | BindingFlags.NonPublic
            | BindingFlags.Static
            | BindingFlags.Instance
            | BindingFlags.GetField | BindingFlags.SetField
            | BindingFlags.GetProperty | BindingFlags.SetProperty
            ;

        // both StartsWith and EndsWith are tested on namespaces and assembly (.dll) names
        readonly static string[] IGNORED_NAMESPACES = new string[]
        {
            "UnityEngine.",
            "UnityEditor.",
            "UnityEditorInternal.",
            "Unity.",
            "TMPro.",
            ".Editor",
            "-Editor",
        };
        // both StartsWith and EndsWith are tested with case insensitive
        readonly static string[] IGNORED_FILE_PATHS = new string[]
        {
            "Packages/",
            ".DLL",
        };
        readonly static string[] DISPOSE_METHODS = new string[]
        {
            "OnDestroy",
            "Dispose",
        };
        readonly static Type[] IGNORED_TYPES = new Type[]
        {
            //typeof(GameObject),
            //typeof(Transform),
        };

        const string INDENT = "    ";
        const string READONLY = "// readonly member is not supported: ";
        const string METHOD_IMPL = "MethodImpl"; //"global::System.Runtime.CompilerServices.MethodImpl";
        const string METHOD_SIGNATURE = "\n[" + METHOD_IMPL + "(" + METHOD_IMPL + @"Options.AggressiveInlining)]
public void Dispose()
{
" + INDENT + @"//<auto-generated>" + nameof(LeakedManagedShellDetector) + @"</auto-generated>
";
        const string LOG_PREFIX = "// LMS Disposer Generator";
        const string MS_DISPOSE = "ManagedShell.Dispose";


        public static bool IsUnityObject(Type t)
        {
            if (t.IsSubclassOf(typeof(UnityEngine.Object)))
            {
                return !IGNORED_TYPES.Contains(t);
            }
            else if (t.IsSubclassOf(typeof(Delegate)))
            {
                return false;
            }
            else if (t.IsArray)
            {
                return IsUnityObject(t.GetElementType());
            }
            else if (t.IsGenericType)
            {
                foreach (var generic in t.GetGenericArguments())
                {
                    if (IsUnityObject(generic))
                        return true;
                }
            }
            return false;
        }


        static StringBuilder _sb;
        public static bool Detect(Type cls, out string generatedDisposerMethod)
        {
            _sb ??= new StringBuilder();
            _sb.Append(METHOD_SIGNATURE);

            bool isCandidate = false;
            foreach (var member in cls.GetMembers(BIND_FLAGS))
            {
                if (member.DeclaringType == typeof(Component) ||
                    member.DeclaringType == typeof(ScriptableObject))
                    continue;

                if (member is FieldInfo f && IsUnityObject(f.FieldType))
                {
                    isCandidate = true;
                    if (f.FieldType.IsSubclassOf(typeof(UnityEngine.Object)))
                    {
                        _sb.AppendLine($"{INDENT}{(f.IsInitOnly ? READONLY : string.Empty)}{MS_DISPOSE}(ref {f.Name});");
                    }
                    else
                    {
                        _sb.AppendLine($"{INDENT}{MS_DISPOSE}({(f.IsInitOnly ? string.Empty : "ref ")}{f.Name});");
                    }
                    //break;
                }
                else if (member is PropertyInfo p && IsUnityObject(p.PropertyType))
                {
                    isCandidate = true;
                    if (p.PropertyType.IsSubclassOf(typeof(UnityEngine.Object)))
                    {
                        _sb.AppendLine($"{INDENT}{(!p.CanWrite ? READONLY : string.Empty)}{MS_DISPOSE}(ref {p.Name});");
                    }
                    else
                    {
                        _sb.AppendLine($"{INDENT}{MS_DISPOSE}({(!p.CanWrite ? string.Empty : "ref ")}{p.Name});");
                    }
                    //break;
                }
            }
            _sb.AppendLine("}");
            _sb.AppendLine("// End of Disposer for " + cls.FullName);
            _sb.AppendLine();

            generatedDisposerMethod = isCandidate ? _sb.ToString() : string.Empty;
            _sb.Clear();
            return isCandidate;
        }


        [MenuItem(MENU_ASSETS)]
        static void GenerateDisposerMethodForSelectedAssets(MenuCommand cmd)
        {
            if (Selection.objects == null)
                return;

            foreach (var sel in Selection.objects)
            {
                Type cls = null;
                if (sel is MonoScript mono)
                {
                    cls = mono.GetClass();
                }

                if (cls == null)
                {
                    UnityEngine.Debug.Log("unsupported type: " + sel.name);
                    continue;
                }

                if (Detect(cls, out var disposerMethod))
                {
                    UnityEngine.Debug.LogWarning($"{LOG_PREFIX}{disposerMethod}");
                }
                else
                {
                    UnityEngine.Debug.Log("No leaks: " + cls.FullName);
                }
            }
        }

        static bool IsIgnored(string name)
        {
            if (name == null)
                return false;

            foreach (var ignore in IGNORED_NAMESPACES)
            {
                if (name.StartsWith(ignore, StringComparison.Ordinal)
                 || name.EndsWith(ignore, StringComparison.Ordinal))
                {
                    return true;
                }
            }
            return false;
        }


        [MenuItem(MENU_MAIN, priority = int.MaxValue / 2)]
        static void DetectLMSPotentials()
        {
            bool detectOnlyUnityOb = EditorUtility.DisplayDialog(nameof(DetectLMSPotentials),
                "Detect only UnityEngine.Object Inheritances?\n\n * Types defined in Packages or DLL are always ignored.",
                "Yes", "No");

            // used to retrieve mono behavior script reference for Debug.Log() context.
            GameObject tmpGO = new GameObject(nameof(LeakedManagedShellDetector));

            foreach (var assem in AppDomain.CurrentDomain.GetAssemblies())
            {
                if (IsIgnored(assem.FullName[..assem.FullName.IndexOf(',')]))
                    continue;

                foreach (var cls in assem.GetTypes())
                {
                    if (detectOnlyUnityOb && !cls.IsSubclassOf(typeof(UnityEngine.Object)))
                        continue;

                    if (IsIgnored(cls.Namespace))
                        continue;

                    if (!Detect(cls, out var disposerMethod))
                        continue;

                    //OnDestroy/Dispose?
                    bool isDisposed = false;
                    foreach (var method in cls.GetMethods(BIND_FLAGS))
                    {
                        if (DISPOSE_METHODS.Contains(method.Name))
                        {
                            isDisposed = true;
                            break;
                        }
                    }
                    if (isDisposed)
                        continue;

                    // dirty code!!
                    UnityEngine.Object debugLogContext = null;
                    try
                    {
                        if (cls.IsSubclassOf(typeof(MonoBehaviour)))
                        {
                            var requiredComponents = GetRequiredComponent(cls);
                            foreach (var rc in requiredComponents)
                            {
                                tmpGO.AddComponent(rc);
                            }
                            debugLogContext = tmpGO.AddComponent(cls);

                            bool isFound = AssetDatabase.TryGetGUIDAndLocalFileIdentifier<Object>(
                                MonoScript.FromMonoBehaviour(debugLogContext as MonoBehaviour),
                                out var GUID, out var localId);

                            Object.DestroyImmediate(debugLogContext);
                            debugLogContext = null;

                            if (isFound)
                            {
                                var path = AssetDatabase.GUIDToAssetPath(GUID);

                                bool isDefinedInIgnoredPath = false;
                                for (int i = 0; i < IGNORED_FILE_PATHS.Length; i++)
                                {
                                    if (path.StartsWith(IGNORED_FILE_PATHS[i], StringComparison.OrdinalIgnoreCase)
                                     || path.EndsWith(IGNORED_FILE_PATHS[i], StringComparison.OrdinalIgnoreCase))
                                    {
                                        isDefinedInIgnoredPath = true;
                                        break;
                                    }
                                }
                                if (isDefinedInIgnoredPath)
                                {
                                    //UnityEngine.Debug.LogError("CLASS IS DEFINED IN IGNORED PATH: " + path);
                                    continue;
                                }

                                debugLogContext = AssetDatabase.LoadAssetAtPath<Object>(path);
                            }
                        }
                    }
                    catch
                    {
                        //hehe
                    }

                    UnityEngine.Debug.LogWarning(LOG_PREFIX
                        + $" \t {assem.FullName[..assem.FullName.IndexOf(',')]}"
                        + $" \t {cls.FullName}\n"
                        //+ $"//{new string('=', 50)}"
                        + $"{disposerMethod}\n"
                        , debugLogContext);

                    if (debugLogContext != null)
                    {
                        var assetPath = AssetDatabase.GetAssetOrScenePath(debugLogContext);
                        if (assetPath == null || assetPath.Length == 0)
                        {
                            Object.DestroyImmediate(debugLogContext);
                        }
                        debugLogContext = null;
                    }
                }
            }

            if (tmpGO != null)
            {
                Object.DestroyImmediate(tmpGO);
                tmpGO = null;
            }
        }


        static Type[] GetRequiredComponent(Type type)
        {
            var found = new System.Collections.Generic.List<Type>();

            foreach (var a in type.GetCustomAttributes<RequireComponent>(true))
            {
                if (a.m_Type0 != null)
                {
                    found.Insert(0, a.m_Type0);
                    found.InsertRange(0, GetRequiredComponent(a.m_Type0));
                }

                if (a.m_Type1 != null)
                {
                    found.Insert(0, a.m_Type1);
                    found.InsertRange(0, GetRequiredComponent(a.m_Type1));
                }

                if (a.m_Type2 != null)
                {
                    found.Insert(0, a.m_Type2);
                    found.InsertRange(0, GetRequiredComponent(a.m_Type2));
                }
            }

            // remove unnecessary
            for (int i = found.Count - 1; i >= 0; i--)
            {
                if (found[i] == typeof(Transform) || found[i].IsAbstract)
                    found.RemoveAt(i);
            }

            return found.Distinct().ToArray();
        }

    }
}

#endif
